"""نماذج Pydantic v2 — مصدر الحقيقة الوحيد لكل الرسائل (§32) وحقول JSONB (§31).

كل التعدادات والنماذج العلنية يعاد تصديرها من هنا بواجهة واحدة؛
المُصدّر ``schemas.export`` يولّد JSON Schema الحتمي إلى generated/،
وسجل ``EVENT_PAYLOAD_MODELS`` يربط كل نوع حدث بنيوي/سيولي (§20) بحمولته
الموثقة.
"""

from __future__ import annotations

from .backtest import (
    BacktestIdentity,
    BacktestMetrics,
    BacktestReport,
    EntrySpec,
    RDistribution,
    RealizedCosts,
    RegimeMetrics,
    SimulatedFill,
    SimulatedTrade,
    WFOProtocolConfig,
    WFOReport,
    WFOSegment,
    WFOWindow,
)
from .enums import (
    DEFAULT_EVENT_WEIGHTS,
    DEFAULT_GROUP_SHARES,
    CostMode,
    DataQuality,
    Direction,
    EventType,
    EvidenceGroup,
    ExitReason,
    HardBlockReason,
    HTFBias,
    IntrabarPolicy,
    LabelState,
    MarketRegime,
    NoTradeSeverity,
    OrderPolicy,
    RejectionBasis,
    ScenarioState,
    ScenarioTemplate,
    SessionType,
    SignalState,
    SizingCapBasis,
    SizingModifierName,
    SoftSuppressionReason,
    SweepClassification,
    WFORole,
)
from .envelope import EVENT_PAYLOAD_MODELS, EventEnvelope, payload_digest, payload_model_for
from .evidence import (
    CALIBRATION_DEFERRAL_REASON,
    AvailabilitySignature,
    CalibrationReport,
    EvidenceRecord,
    ExplanationObject,
    FusionSnapshot,
    GroupScore,
    validate_explanation_completeness,
)
from .execution import LatencyRecord, OrderIntent, SlippageRecord
from .learning import ExperienceRecord
from .liquidity import (
    BreakAcceptEventPayload,
    LiquiditySide,
    LiquiditySourceType,
    LiquidityZone,
    SweepEventPayload,
    ZoneState,
)
from .market import Candle, FootprintBar, MarketStateSnapshot, TradeEvent
from .orderflow import (
    AbsorbedPressure,
    AbsorptionConditions,
    AbsorptionEventPayload,
    ExhaustionEventPayload,
    FlowContinuationEventPayload,
    FlowDirection,
    ImbalanceClusterEventPayload,
    ImbalanceSide,
)
from .patterns import (
    CANDLE_FEATURE_KEYS,
    AnchorPoint,
    CandlePatternEventPayload,
    CandlePatternFamily,
    ClassicalPatternEventPayload,
    ClassicalPatternType,
    PatternDirection,
    PatternStatus,
)
from .risk import (
    CostBreakdown,
    EvaluationContext,
    MacroEventWindow,
    NoTradeExplanation,
    RewardRiskEstimate,
    RiskDecision,
    SizingModifier,
    SizingResult,
    StructuralStop,
)
from .scenario import (
    InvalidationRule,
    PriceZone,
    Scenario,
    ScenarioTransition,
    TargetZone,
    TriggerDefinition,
)
from .structure import (
    BreakDirection,
    DisplacementEventPayload,
    FvgDirection,
    FvgEventPayload,
    FvgState,
    OrderBlockEventPayload,
    PremiumDiscountEventPayload,
    PremiumDiscountSide,
    StructureBreakPayload,
    StructureConsequence,
    Swing,
    SwingDirection,
    SwingScope,
)

__version__ = "0.1.0"

# إصدار المخططات — يُرفع عند أي تغيير كسر في عقود الرسائل (§32: versioned contracts)
SCHEMA_VERSION = "1.0.0"

# الواجهة العلنية الكاملة — مرتبة ترتيبًا حتميًا (RUF022): الثوابت العليا
# ثم الفئات ثم الأسماء السفلية (__version__ قبل الدوال — ترتيب بايتات
# الشرطة السفلية). كل تعدادة ونموذج علني في الحزمة موجود هنا.
__all__ = [
    "CALIBRATION_DEFERRAL_REASON",
    "CANDLE_FEATURE_KEYS",
    "DEFAULT_EVENT_WEIGHTS",
    "DEFAULT_GROUP_SHARES",
    "EVENT_PAYLOAD_MODELS",
    "SCHEMA_VERSION",
    "AbsorbedPressure",
    "AbsorptionConditions",
    "AbsorptionEventPayload",
    "AnchorPoint",
    "AvailabilitySignature",
    "BacktestIdentity",
    "BacktestMetrics",
    "BacktestReport",
    "BreakAcceptEventPayload",
    "BreakDirection",
    "CalibrationReport",
    "Candle",
    "CandlePatternEventPayload",
    "CandlePatternFamily",
    "ClassicalPatternEventPayload",
    "ClassicalPatternType",
    "CostBreakdown",
    "CostMode",
    "DataQuality",
    "Direction",
    "DisplacementEventPayload",
    "EntrySpec",
    "EvaluationContext",
    "EventEnvelope",
    "EventType",
    "EvidenceGroup",
    "EvidenceRecord",
    "ExhaustionEventPayload",
    "ExitReason",
    "ExperienceRecord",
    "ExplanationObject",
    "FlowContinuationEventPayload",
    "FlowDirection",
    "FootprintBar",
    "FusionSnapshot",
    "FvgDirection",
    "FvgEventPayload",
    "FvgState",
    "GroupScore",
    "HTFBias",
    "HardBlockReason",
    "ImbalanceClusterEventPayload",
    "ImbalanceSide",
    "IntrabarPolicy",
    "InvalidationRule",
    "LabelState",
    "LatencyRecord",
    "LiquiditySide",
    "LiquiditySourceType",
    "LiquidityZone",
    "MacroEventWindow",
    "MarketRegime",
    "MarketStateSnapshot",
    "NoTradeExplanation",
    "NoTradeSeverity",
    "OrderBlockEventPayload",
    "OrderIntent",
    "OrderPolicy",
    "PatternDirection",
    "PatternStatus",
    "PremiumDiscountEventPayload",
    "PremiumDiscountSide",
    "PriceZone",
    "RDistribution",
    "RealizedCosts",
    "RegimeMetrics",
    "RejectionBasis",
    "RewardRiskEstimate",
    "RiskDecision",
    "Scenario",
    "ScenarioState",
    "ScenarioTemplate",
    "ScenarioTransition",
    "SessionType",
    "SignalState",
    "SimulatedFill",
    "SimulatedTrade",
    "SizingCapBasis",
    "SizingModifier",
    "SizingModifierName",
    "SizingResult",
    "SlippageRecord",
    "SoftSuppressionReason",
    "StructuralStop",
    "StructureBreakPayload",
    "StructureConsequence",
    "SweepClassification",
    "SweepEventPayload",
    "Swing",
    "SwingDirection",
    "SwingScope",
    "TargetZone",
    "TradeEvent",
    "TriggerDefinition",
    "WFOProtocolConfig",
    "WFOReport",
    "WFORole",
    "WFOSegment",
    "WFOWindow",
    "ZoneState",
    "__version__",
    "payload_digest",
    "payload_model_for",
    "validate_explanation_completeness",
]
